name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v4
        with:
          go-version-file: ./go.mod

      - name: setup task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Builds the binary into the bin/ directory
      - name: build
        run: |-
          task build

      - name: upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: frizbee
          path: bin/frizbee

  cover:
    name: Coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v4
        with:
          go-version-file: 'go.mod'

      - name: setup task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run coverage
        run: task cover

      # Using gcov didn't seem to work for the coveralls app, so we convert it to lcov
      - name: Try converting to LCOV
        run: go run github.com/jandelgado/gcov2lcov@latest -infile=./coverage.out -outfile=./coverage.lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2.2.3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v4
        with:
          go-version-file: ./go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v4
        with:
          go-version-file: ./go.mod

      - name: setup task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: |-
          task test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Checks that the github workflows are valid using this same tool
  frizbee:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: download artifact
        uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 #v4.1.3
        with:
          name: frizbee
          path: bin/

      - name: Make frizbee executable
        run: |-
          chmod +x bin/frizbee

      - name: Frizbee
        run: |-
          bin/frizbee ghactions --dry-run --error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
